name: Amazon Jobs Tracker
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  check-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Using an older version for better compatibility
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install certifi==2021.10.8
        python -m pip install "pymongo[srv]"==3.11
        python -m pip install urllib3==1.26.6
        
    - name: Show certificate info
      run: |
        python -c "import certifi; print('Certifi location:', certifi.where())"
        ls -l $(python -c "import certifi; print(certifi.where())")
    
    - name: Run job tracker
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        CC_EMAIL: ${{ secrets.CC_EMAIL }}
        BCC_RECIPIENTS: ${{ secrets.BCC_RECIPIENTS }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: python amazonjobscript.py
